# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.TextField()),
                ('cat_table_name', models.TextField()),
            ],
        ),
    ]
